/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJNI */

#ifndef _Included_HelloJNI
#define _Included_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloJNI_sayHello
  (JNIEnv *, jobject);

// /*
//  * Class:     HelloJNI
//  * Method:    filterGreater
//  * Signature: (D[D)[D
//  */
// JNIEXPORT jdoubleArray JNICALL Java_HelloJNI_filterGreater
//   (JNIEnv *, jobject, jdouble, jdoubleArray);

// /*
//  * Class:     HelloJNI
//  * Method:    test
//  * Signature: (FF)F
//  */
// JNIEXPORT jfloat JNICALL Java_HelloJNI_test
//   (JNIEnv *, jobject, jfloat, jfloat);

// /*
//  * Class:     HelloJNI
//  * Method:    addArray
//  * Signature: ([I[I)[I
//  */
// JNIEXPORT jintArray JNICALL Java_HelloJNI_addArray
//   (JNIEnv *, jobject, jintArray, jintArray);

// /*
//  * Class:     HelloJNI
//  * Method:    maskGreater
//  * Signature: (I[I)[Z
//  */
// JNIEXPORT jbooleanArray JNICALL Java_HelloJNI_maskGreater
//   (JNIEnv *, jobject, jint, jintArray);

// /*
//  * Class:     HelloJNI
//  * Method:    customAddArray
//  * Signature: ([I[I)[I
//  */
// JNIEXPORT jintArray JNICALL Java_HelloJNI_customAddArray
//   (JNIEnv *, jobject, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
